api = "0.5"

[buildpack]
  id = "paketo-community/pip"
  name = "Paketo Pip Buildpack"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "120355ab3197f76c8811ce40537a5446ba107eaccd8efe18369e03698eb595f0"
    source = "https://files.pythonhosted.org/packages/b7/2d/ad02de84a4c9fd3b1958dc9fb72764de1aa2605a9d7e943837be6ad82337/pip-21.0.1.tar.gz"
    source_sha256 = "99bbde183ec5ec037318e774b0d8ae0a64352fe53b2c7fd630be1d07e94f41e5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_21.0.1_linux_noarch_any-stack_120355ab.tgz"
    version = "21.0.1"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "2f2f85ccff0d42208bec57844221d0a1d55c74d4d0638ab709155cf6b2e45b74"
    source = "https://files.pythonhosted.org/packages/94/b0/e10bdc8809c81796c80aa3644a8e3dc16594fb1bd68f5996929f26cad980/pip-21.1.1.tar.gz"
    source_sha256 = "51ad01ddcd8de923533b01a870e7b987c2eb4d83b50b89e1bf102723ff9fed8b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_21.1.1_linux_noarch_any-stack_2f2f85cc.tgz"
    version = "21.1.1"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
