api = "0.2"

[buildpack]
  id = "paketo-community/pip"
  name = "Paketo Pip Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "6ec0d64e42bc775fd55639767a2760466cc013ee8bb0aa3db32f031694b37d34"
    source = "https://files.pythonhosted.org/packages/73/8e/7774190ac616c69194688ffce7c1b2a097749792fea42e390e7ddfdef8bc/pip-20.2.2.tar.gz"
    source_sha256 = "58a3b0b55ee2278104165c7ee7bc8e2db6f635067f3c66cf637113ec5aa71584"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_20.2.2_linux_noarch_any-stack_6ec0d64e.tgz"
    version = "20.2.2"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "0bc0f8ff98820f35311341226006c72f3550b1e54ef4684229185d73633db273"
    source = "https://files.pythonhosted.org/packages/59/64/4718738ffbc22d98b5223dbd6c5bb87c476d83a4c71719402935170064c7/pip-20.2.3.tar.gz"
    source_sha256 = "30c70b6179711a7c4cf76da89e8a0f5282279dfb0278bec7b94134be92543b6d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_20.2.3_linux_noarch_any-stack_0bc0f8ff.tgz"
    version = "20.2.3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
