api = "0.2"

[buildpack]
  id = "paketo-community/pip"
  name = "Paketo Pip Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "0126d3113e2152315c379b473d9066fbbec9bd2b7c24d4b226c0db11d0209612"
    source = "https://files.pythonhosted.org/packages/03/41/6da553f689d530bc2c337d2c496a40dc9c0fdc6481e5df1f3ee3b8574479/pip-20.3.tar.gz"
    source_sha256 = "9ae7ca6656eac22d2a9b49d024fc24e00f68f4c4d4db673d2d9b525c3dea6e0e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_20.3_linux_noarch_any-stack_0126d311.tgz"
    version = "20.3"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "da935b904abe6eae4b1f5e965988bcdc016259e68dfca31296a0328d445a1428"
    source = "https://files.pythonhosted.org/packages/cb/5f/ae1eb8bda1cde4952bd12e468ab8a254c345a0189402bf1421457577f4f3/pip-20.3.1.tar.gz"
    source_sha256 = "43f7d3811f05db95809d39515a5111dd05994965d870178a4fe10d5482f9d2e2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_20.3.1_linux_noarch_any-stack_da935b90.tgz"
    version = "20.3.1"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
