api = "0.5"

[buildpack]
  id = "paketo-community/pip"
  name = "Paketo Pip Buildpack"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "4780d550d36604b779d17b60655d03c07427eb9499cb7b9da15802bc36fe01e4"
    source = "https://files.pythonhosted.org/packages/b1/44/6e26d5296b83c6aac166e48470d57a00d3ed1f642e89adc4a4e412a01643/pip-21.1.2.tar.gz"
    source_sha256 = "eb5df6b9ab0af50fe1098a52fd439b04730b6e066887ff7497357b9ebd19f79b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_21.1.2_linux_noarch_any-stack_4780d550.tgz"
    version = "21.1.2"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "79fd2c5ca13c9d140dcef88e47a392f4bdb9439ea30cee4580e2aee16a519472"
    source = "https://files.pythonhosted.org/packages/4d/0c/3b63fe024414a8a48661cf04f0993d4b2b8ef92daed45636474c018cd5b7/pip-21.1.3.tar.gz"
    source_sha256 = "b5b1eb91b36894bd01b8e5a56a422c2f3838573da0b0a1c63a096bb454e3b23f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_21.1.3_linux_noarch_any-stack_79fd2c5c.tgz"
    version = "21.1.3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
