api = "0.2"

[buildpack]
  id = "paketo-community/pip"
  name = "Paketo Pip Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "bee2c93d3f42358ab1d3f1dc65b230592348ac174025811f08369438347c6615"
    source = "https://files.pythonhosted.org/packages/0b/f5/be8e741434a4bf4ce5dbc235aa28ed0666178ea8986ddc10d035023744e6/pip-20.2.4.tar.gz"
    source_sha256 = "85c99a857ea0fb0aedf23833d9be5c40cf253fe24443f0829c7b472e23c364a1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_20.2.4_linux_noarch_any-stack_bee2c93d.tgz"
    version = "20.2.4"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "0126d3113e2152315c379b473d9066fbbec9bd2b7c24d4b226c0db11d0209612"
    source = "https://files.pythonhosted.org/packages/03/41/6da553f689d530bc2c337d2c496a40dc9c0fdc6481e5df1f3ee3b8574479/pip-20.3.tar.gz"
    source_sha256 = "9ae7ca6656eac22d2a9b49d024fc24e00f68f4c4d4db673d2d9b525c3dea6e0e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_20.3_linux_noarch_any-stack_0126d311.tgz"
    version = "20.3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
