api = "0.2"

[buildpack]
  id = "paketo-community/pip"
  name = "Paketo Pip Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "51d2bf2634710bacaf62f7b4d3e85533d0ed5e03ffc25bd257fc96b499075d7e"
    source = "https://files.pythonhosted.org/packages/9e/24/bc928987f35dd0167f21b13a1777c21b9c5917c9894cff93f1c1a6cb8f3b/pip-21.0.tar.gz"
    source_sha256 = "b330cf6467afd5d15f4c1c56f5c95e56a2bfb941c869bed4c1aa517bcb16de25"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_21.0_linux_noarch_any-stack_51d2bf26.tgz"
    version = "21.0"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "120355ab3197f76c8811ce40537a5446ba107eaccd8efe18369e03698eb595f0"
    source = "https://files.pythonhosted.org/packages/b7/2d/ad02de84a4c9fd3b1958dc9fb72764de1aa2605a9d7e943837be6ad82337/pip-21.0.1.tar.gz"
    source_sha256 = "99bbde183ec5ec037318e774b0d8ae0a64352fe53b2c7fd630be1d07e94f41e5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_21.0.1_linux_noarch_any-stack_120355ab.tgz"
    version = "21.0.1"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
