api = "0.2"

[buildpack]
  id = "org.cloudfoundry.pip"
  name = "Pip Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "7ead40747512e9ec77ca1f87af67db8ab011ced48c66933d8e9d8fc094ebd95f"
    source = "https://files.pythonhosted.org/packages/8e/76/66066b7bc71817238924c7e4b448abdb17eb0c92d645769c223f9ace478f/pip-20.0.2.tar.gz"
    source_sha256 = "7db0c8ea4c7ea51c8049640e8e6e7fde949de672bfa4949920675563a5a6967f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip-20.0.2-any-stack-7ead4074.tgz"
    version = "20.0.2"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "d4cbb7ebb903193d3c5e677eb51aa2bbf6eb2a2271e338ecb1b46f9483890ef7"
    source = "https://files.pythonhosted.org/packages/08/25/f204a6138dade2f6757b4ae99bc3994aac28a5602c97ddb2a35e0e22fbc4/pip-20.1.1.tar.gz"
    source_sha256 = "27f8dc29387dd83249e06e681ce087e6061826582198a425085e0bf4c1cf3a55"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_20.1.1_linux_noarch_any-stack_d4cbb7eb.tgz"
    version = "20.1.1"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
