api = "0.2"

[buildpack]
  id = "paketo-community/pip"
  name = "Pip Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "c6160688503c41590f31e3fdc534e4ed7e0a71d672ef7348eb8558a01f308baa"
    source = "https://files.pythonhosted.org/packages/28/af/2c76c8aa46ccdf7578b83d97a11a2d1858794d4be4a1610ade0d30182e8b/pip-20.0.1.tar.gz"
    source_sha256 = "3cebbac2a1502e09265f94e5717408339de846b3c0f0ed086d7b817df9cab822"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip-20.0.1-any-stack-c6160688.tgz"
    version = "20.0.1"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "7ead40747512e9ec77ca1f87af67db8ab011ced48c66933d8e9d8fc094ebd95f"
    source = "https://files.pythonhosted.org/packages/8e/76/66066b7bc71817238924c7e4b448abdb17eb0c92d645769c223f9ace478f/pip-20.0.2.tar.gz"
    source_sha256 = "7db0c8ea4c7ea51c8049640e8e6e7fde949de672bfa4949920675563a5a6967f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip-20.0.2-any-stack-7ead4074.tgz"
    version = "20.0.2"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
